/* Generated By:JavaCC: Do not edit this line. AnalizadorSConstants.java */
package Analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SIMU = 5;
  /** RegularExpression Id. */
  int EJEC = 6;
  /** RegularExpression Id. */
  int RECURSO = 7;
  /** RegularExpression Id. */
  int TIEMPO = 8;
  /** RegularExpression Id. */
  int PROC = 9;
  /** RegularExpression Id. */
  int ASIG = 10;
  /** RegularExpression Id. */
  int LIBE = 11;
  /** RegularExpression Id. */
  int TERMI = 12;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int MINUS = 14;
  /** RegularExpression Id. */
  int MULTIPLY = 15;
  /** RegularExpression Id. */
  int DIVIDE = 16;
  /** RegularExpression Id. */
  int CONSTANT = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Simulacion\"",
    "\"Ejecucion\"",
    "\"Recurso\"",
    "\"Tiempo\"",
    "\"Proceso\"",
    "\"Asignar\"",
    "\"Liberar\"",
    "\"Terminar\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<CONSTANT>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\"R\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
